# Generated by Django 2.1.2 on 2020-08-02 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('nick_name', models.CharField(default='', max_length=50)),
                ('head_img', models.CharField(db_index=True, default='https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=38616266,2952961838&fm=26&gp=0.jpg', max_length=500)),
                ('content', models.TextField(default='该用户很懒,什么也没写!')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
