# Generated by Django 2.1.2 on 2020-08-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
