# Generated by Django 2.1.2 on 2020-08-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_picture_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='index',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
