# Generated by Django 2.1.2 on 2020-10-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ('-create_time',)},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-create_time',)},
        ),
        migrations.AlterField(
            model_name='data',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
